/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rfid;

import com.alee.extended.image.WebImage;
import com.alee.extended.statusbar.WebStatusLabel;
import com.alee.managers.language.data.TooltipWay;
import com.alee.managers.tooltip.TooltipManager;
import database.DatabaseImplement;
import database.MySqlConnections;
import database.StudentsList;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author alienware
 */
public class Addnewuser extends com.alee.laf.desktoppane.WebInternalFrame {

    /**
     * Creates new form Addnewuser
     *
     */
    public Addnewuser() {
        initComponents();
        webButton1.setRound(20);
        txtName1.setMargin(0, 0, 0, 2);
        txtCardID1.setMargin(0, 0, 0, 2);
        txtName1.setTrailingComponent(new WebImage(loadIcon("user-info.png")));
        txtCardID1.setTrailingComponent(new WebImage(loadIcon("cardauth.png")));
        txtStartDate.setInputPromptPosition(SwingConstants.CENTER);
        txtEndDate.setInputPromptPosition(SwingConstants.CENTER);
        TooltipManager.setTooltip(txtName1, loadIcon("tooltip.png"), "ФИО, это важно подано", TooltipWay.down, 0);
    }

    private URL getIconResource(String path) {
        return getClass().getResource("icons/" + path);
    }

    public ImageIcon loadIcon(String path) {
        return new ImageIcon(getIconResource(path));
    }

    public BufferedImage LoadImage(final String path) {
        BufferedImage image = null;
        try {
            image = ImageIO.read(getClass().getResource("image/" + path));
            return image;
        } catch (IOException e) {
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        jPanel1 = new javax.swing.JPanel();
        txtCardID1 = new com.alee.laf.text.WebTextField();
        webButton3 = new com.alee.laf.button.WebButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdstudint = new javax.swing.JRadioButton();
        rdtechier = new javax.swing.JRadioButton();
        rdadmin = new javax.swing.JRadioButton();
        txtName1 = new com.alee.laf.text.WebTextField();
        txtStartDate = new com.alee.extended.date.WebDateField();
        jLabel7 = new javax.swing.JLabel();
        txtEndDate = new com.alee.extended.date.WebDateField();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new com.alee.laf.text.WebTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBirthday = new com.alee.extended.date.WebDateField();
        jLabel9 = new javax.swing.JLabel();
        panelStudint = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFamilyName = new com.alee.laf.text.WebTextField();
        txtFamilyPhone = new com.alee.laf.text.WebTextField();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        jLabel1 = new javax.swing.JLabel();
        webMultiLineLabel1 = new com.alee.extended.label.WebMultiLineLabel();
        webButton1 = new com.alee.laf.button.WebButton();

        setTitle("Создать нового пользователя");

        webPanel1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        txtCardID1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        txtCardID1.setMargin(new java.awt.Insets(0, 0, 0, 2));
        txtCardID1.setRound(7);
        txtCardID1.setWebColored(true);

        webButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rfid/icons/settings.png"))); // NOI18N
        webButton3.setText("сканирование");
        webButton3.setToolTipText("");
        webButton3.setFont(webButton3.getFont().deriveFont(webButton3.getFont().getSize()+1f));
        webButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("ФИО");

        jLabel5.setText("Карта");

        jLabel6.setText("категория");

        buttonGroup1.add(rdstudint);
        rdstudint.setSelected(true);
        rdstudint.setText("Ученик");
        rdstudint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdstudintActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtechier);
        rdtechier.setText("учитель");
        rdtechier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtechierActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdadmin);
        rdadmin.setText("административный");
        rdadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdadminActionPerformed(evt);
            }
        });

        txtName1.setFont(txtName1.getFont().deriveFont(txtName1.getFont().getSize()+3f));
        txtName1.setInputPrompt("");
        txtName1.setMargin(new java.awt.Insets(0, 0, 0, 2));
        txtName1.setName(""); // NOI18N
        txtName1.setRound(7);
        txtName1.setWebColored(true);

        txtStartDate.setDragEnabled(true);
        txtStartDate.setInheritsPopupMenu(true);
        txtStartDate.setRound(7);
        txtStartDate.setSelectionEnd(2);
        txtStartDate.setWebColored(true);

        jLabel7.setText("Дата начала");

        txtEndDate.setRound(7);
        txtEndDate.setWebColored(true);

        jLabel8.setText("Дата окончания");

        txtPhone.setRound(7);
        txtPhone.setWebColored(true);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jLabel2.setText("Телефон");

        txtBirthday.setDragEnabled(true);
        txtBirthday.setInheritsPopupMenu(true);
        txtBirthday.setRound(7);
        txtBirthday.setSelectionEnd(2);
        txtBirthday.setWebColored(true);

        jLabel9.setText("Дата рождения");

        jLabel3.setText("ФИО родителя");

        jLabel10.setText("Телефон родителя");

        txtFamilyName.setRound(7);
        txtFamilyName.setWebColored(true);
        txtFamilyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFamilyNameActionPerformed(evt);
            }
        });

        txtFamilyPhone.setRound(7);
        txtFamilyPhone.setWebColored(true);
        txtFamilyPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFamilyPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStudintLayout = new javax.swing.GroupLayout(panelStudint);
        panelStudint.setLayout(panelStudintLayout);
        panelStudintLayout.setHorizontalGroup(
            panelStudintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStudintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudintLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addComponent(txtFamilyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelStudintLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(23, 23, 23)
                        .addComponent(txtFamilyPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelStudintLayout.setVerticalGroup(
            panelStudintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudintLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelStudintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtFamilyName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelStudintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(txtFamilyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStudint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(55, 55, 55)
                                .addComponent(rdstudint)
                                .addGap(18, 18, 18)
                                .addComponent(rdtechier)
                                .addGap(18, 18, 18)
                                .addComponent(rdadmin))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCardID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(webButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(rdstudint)
                    .addComponent(rdtechier)
                    .addComponent(rdadmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtCardID1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelStudint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rfid/image/addnew.png"))); // NOI18N
        webPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);

        webMultiLineLabel1.setText("В этом окне вы можете добавить нового пользователя с его идентификационной картой RFID,\nплюс дата начала его карты и дата окончания.");
        webMultiLineLabel1.setDrawShade(true);
        webMultiLineLabel1.setFont(webMultiLineLabel1.getFont());
        webMultiLineLabel1.setIconTextGap(6);
        webPanel2.add(webMultiLineLabel1, java.awt.BorderLayout.CENTER);

        webButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rfid/icons/on.png"))); // NOI18N
        webButton1.setText("Сохранить");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(webPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(webPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(webButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdstudintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdstudintActionPerformed
        if (!panelStudint.isVisible()) {
            panelStudint.setVisible(true);
        }
    }//GEN-LAST:event_rdstudintActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void webButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton3ActionPerformed
        WebStatusLabel First = new WebStatusLabel();
        WebStatusLabel Second = new WebStatusLabel();
        Scaning Scan = new Scaning(First, Second);
        Scan.run();
        while (Second.getText().isEmpty()) {
            txtCardID1.setText(Second.getText());
        }

    }//GEN-LAST:event_webButton3ActionPerformed

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        Map<String, String> map = new HashMap<>();
        String Name = txtName1.getText();
        String CardNumber = txtCardID1.getText();
        if (rdstudint.isSelected()) {
            map.put("isStudent", "1");
        } else if (rdtechier.isSelected()) {
            map.put("isTecher", "1");
        } else if (rdadmin.isSelected()) {
            map.put("isAdmin", "1");
        }
        String Phone = txtPhone.getText();
        String DateStart = txtStartDate.getText();
        String DateEnd = txtEndDate.getText();
        String Birthday = txtBirthday.getText();
        String FamilyName = txtFamilyName.getText();
        String FamilyPhone = txtFamilyPhone.getText();

        map.put("name", Name);
        map.put("cardid", CardNumber);
        map.put("phonenumber", Phone);
        map.put("astart", DateStart);
        map.put("aend", DateEnd);
        map.put("birthdate", Birthday);
        map.put("parentphone", FamilyPhone);
        map.put("parentname", FamilyName);
        map.put("lastlogin", "0000-00-00 00:00:00");
        MySqlConnections MySQLDB = new MySqlConnections();
        if (MySQLDB.set("Users", map)) {
            txtName1.setText("");
            txtCardID1.setText("");
            rdstudint.setSelected(true);
            rdtechier.setSelected(false);
            rdadmin.setSelected(false);
            txtPhone.setText("");
            txtBirthday.setText("");
            txtFamilyName.setText("");
            txtFamilyPhone.setText("");
            txtStartDate.setText("");
            txtEndDate.setText("");
            if (!panelStudint.isVisible()) {
                panelStudint.setVisible(true);
            }
            StudentsList NSL = null;
            if (rdstudint.isSelected()) {
                NSL = new DatabaseImplement().GetStudent(Name);
            } else if (rdtechier.isSelected()) {
                NSL = new DatabaseImplement().GetTetcher(Name);
            }
            map.clear();
            map.put("userid", String.valueOf(NSL.getUserID()));
            map.put("amount", "0");
            if (MySQLDB.set("balance", map)) {
                new helper.helper().setWarningMsg(this, "Данные записаны");
            }
        } else {
            new helper.helper().setErrorMsg(this, "Эти данные существуют");
        }
    }//GEN-LAST:event_webButton1ActionPerformed

    private void txtFamilyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFamilyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFamilyNameActionPerformed

    private void txtFamilyPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFamilyPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFamilyPhoneActionPerformed

    private void rdtechierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtechierActionPerformed
        if (panelStudint.isVisible()) {
            panelStudint.setVisible(false);
        }
    }//GEN-LAST:event_rdtechierActionPerformed

    private void rdadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdadminActionPerformed
        if (panelStudint.isVisible()) {
            panelStudint.setVisible(false);
        }
    }//GEN-LAST:event_rdadminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelStudint;
    private javax.swing.JRadioButton rdadmin;
    private javax.swing.JRadioButton rdstudint;
    private javax.swing.JRadioButton rdtechier;
    private com.alee.extended.date.WebDateField txtBirthday;
    private com.alee.laf.text.WebTextField txtCardID1;
    private com.alee.extended.date.WebDateField txtEndDate;
    private com.alee.laf.text.WebTextField txtFamilyName;
    private com.alee.laf.text.WebTextField txtFamilyPhone;
    private com.alee.laf.text.WebTextField txtName1;
    private com.alee.laf.text.WebTextField txtPhone;
    private com.alee.extended.date.WebDateField txtStartDate;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton3;
    private com.alee.extended.label.WebMultiLineLabel webMultiLineLabel1;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
